name: water_management_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^2.0.17                  

  cupertino_icons: ^1.0.8
  mqtt_client: ^10.8.0
  http: ^1.3.0
  provider: ^6.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  syncfusion_flutter_gauges: ^28.2.12
  syncfusion_flutter_charts: ^28.2.12
  
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Uncommented for better linting

flutter:
  uses-material-design: true
  assets:
    - assets/images/vector.svg
    - assets/images/SignIn-1.png
    - assets/images/StartedStartedBackground-1.png
    - assets/images/StartedScreenleaf.png
    - assets/images/Startedleaf2.png
    - assets/images/Register.jpg
  
  



